spring:
  profiles:
    active: ${ENV_PROFILE:qa}


logging:gi
  level:
    root: info
    br.com: debug
  pattern:
    console: "%d{ISO8601} %-5level %logger{0}.%M:%L - %msg %n"

report:
  name: "RelatorioTestes.html"
  path: "reports/"

alguma:
  variavel:
    github: ${VARIAVEL}